/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CitizensRouteImport } from './routes/citizens'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as ApiCitizenAiRouteImport } from './routes/api/citizen-ai'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedSelfEmployedRouteRouteImport } from './routes/_authenticated/self-employed/route'
import { Route as AuthenticatedIpRouteRouteImport } from './routes/_authenticated/ip/route'
import { Route as AuthenticatedCitizenRouteRouteImport } from './routes/_authenticated/citizen/route'
import { Route as AuthenticatedSelfEmployedIndexRouteImport } from './routes/_authenticated/self-employed/index'
import { Route as AuthenticatedIpIndexRouteImport } from './routes/_authenticated/ip/index'
import { Route as AuthenticatedCitizenIndexRouteImport } from './routes/_authenticated/citizen/index'
import { Route as AuthenticatedSelfEmployedSupportRouteImport } from './routes/_authenticated/self-employed/support'
import { Route as AuthenticatedSelfEmployedSettingsRouteImport } from './routes/_authenticated/self-employed/settings'
import { Route as AuthenticatedSelfEmployedServicesRouteImport } from './routes/_authenticated/self-employed/services'
import { Route as AuthenticatedSelfEmployedQrRouteImport } from './routes/_authenticated/self-employed/qr'
import { Route as AuthenticatedSelfEmployedPaymentsRouteImport } from './routes/_authenticated/self-employed/payments'
import { Route as AuthenticatedSelfEmployedInvoicesRouteImport } from './routes/_authenticated/self-employed/invoices'
import { Route as AuthenticatedSelfEmployedIncomeRouteImport } from './routes/_authenticated/self-employed/income'
import { Route as AuthenticatedSelfEmployedDocumentsRouteImport } from './routes/_authenticated/self-employed/documents'
import { Route as AuthenticatedSelfEmployedClientsRouteImport } from './routes/_authenticated/self-employed/clients'
import { Route as AuthenticatedSelfEmployedAnalyticsRouteImport } from './routes/_authenticated/self-employed/analytics'
import { Route as AuthenticatedSelfEmployedAiRouteImport } from './routes/_authenticated/self-employed/ai'
import { Route as AuthenticatedIpWarehouseRouteImport } from './routes/_authenticated/ip/warehouse'
import { Route as AuthenticatedIpTeamRouteImport } from './routes/_authenticated/ip/team'
import { Route as AuthenticatedIpTaxesRouteImport } from './routes/_authenticated/ip/taxes'
import { Route as AuthenticatedIpSuppliersRouteImport } from './routes/_authenticated/ip/suppliers'
import { Route as AuthenticatedIpSettingsRouteImport } from './routes/_authenticated/ip/settings'
import { Route as AuthenticatedIpSbpRouteImport } from './routes/_authenticated/ip/sbp'
import { Route as AuthenticatedIpSalesRouteImport } from './routes/_authenticated/ip/sales'
import { Route as AuthenticatedIpQrRouteImport } from './routes/_authenticated/ip/qr'
import { Route as AuthenticatedIpPayrollRouteImport } from './routes/_authenticated/ip/payroll'
import { Route as AuthenticatedIpPaymentsRouteImport } from './routes/_authenticated/ip/payments'
import { Route as AuthenticatedIpOrdersRouteImport } from './routes/_authenticated/ip/orders'
import { Route as AuthenticatedIpMarketplaceRouteImport } from './routes/_authenticated/ip/marketplace'
import { Route as AuthenticatedIpIntegrationsRouteImport } from './routes/_authenticated/ip/integrations'
import { Route as AuthenticatedIpFinanceRouteImport } from './routes/_authenticated/ip/finance'
import { Route as AuthenticatedIpDocumentsRouteImport } from './routes/_authenticated/ip/documents'
import { Route as AuthenticatedIpDigitalRubleRouteImport } from './routes/_authenticated/ip/digital-ruble'
import { Route as AuthenticatedIpCustomersRouteImport } from './routes/_authenticated/ip/customers'
import { Route as AuthenticatedIpCrmRouteImport } from './routes/_authenticated/ip/crm'
import { Route as AuthenticatedIpCatalogRouteImport } from './routes/_authenticated/ip/catalog'
import { Route as AuthenticatedIpBankAccountsRouteImport } from './routes/_authenticated/ip/bank-accounts'
import { Route as AuthenticatedIpAnalyticsRouteImport } from './routes/_authenticated/ip/analytics'
import { Route as AuthenticatedIpAiRouteImport } from './routes/_authenticated/ip/ai'
import { Route as AuthenticatedCitizenWalletRouteImport } from './routes/_authenticated/citizen/wallet'
import { Route as AuthenticatedCitizenTransfersRouteImport } from './routes/_authenticated/citizen/transfers'
import { Route as AuthenticatedCitizenSupportRouteImport } from './routes/_authenticated/citizen/support'
import { Route as AuthenticatedCitizenSubscriptionsRouteImport } from './routes/_authenticated/citizen/subscriptions'
import { Route as AuthenticatedCitizenSettingsRouteImport } from './routes/_authenticated/citizen/settings'
import { Route as AuthenticatedCitizenQrRouteImport } from './routes/_authenticated/citizen/qr'
import { Route as AuthenticatedCitizenProfileRouteImport } from './routes/_authenticated/citizen/profile'
import { Route as AuthenticatedCitizenPaymentsRouteImport } from './routes/_authenticated/citizen/payments'
import { Route as AuthenticatedCitizenNotificationsRouteImport } from './routes/_authenticated/citizen/notifications'
import { Route as AuthenticatedCitizenHistoryRouteImport } from './routes/_authenticated/citizen/history'
import { Route as AuthenticatedCitizenDocumentsRouteImport } from './routes/_authenticated/citizen/documents'
import { Route as AuthenticatedCitizenAnalyticsRouteImport } from './routes/_authenticated/citizen/analytics'
import { Route as AuthenticatedCitizenAiRouteImport } from './routes/_authenticated/citizen/ai'
import { Route as AuthenticatedSelfEmployedInvoicesNewRouteImport } from './routes/_authenticated/self-employed/invoices.new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizensRoute = CitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ApiCitizenAiRoute = ApiCitizenAiRouteImport.update({
  id: '/citizen-ai',
  path: '/citizen-ai',
  getParentRoute: () => ApiRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelfEmployedRouteRoute =
  AuthenticatedSelfEmployedRouteRouteImport.update({
    id: '/self-employed',
    path: '/self-employed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIpRouteRoute = AuthenticatedIpRouteRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitizenRouteRoute =
  AuthenticatedCitizenRouteRouteImport.update({
    id: '/citizen',
    path: '/citizen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedIndexRoute =
  AuthenticatedSelfEmployedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedIpIndexRoute = AuthenticatedIpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedCitizenIndexRoute =
  AuthenticatedCitizenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedSelfEmployedSupportRoute =
  AuthenticatedSelfEmployedSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedSettingsRoute =
  AuthenticatedSelfEmployedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedServicesRoute =
  AuthenticatedSelfEmployedServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedQrRoute =
  AuthenticatedSelfEmployedQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedPaymentsRoute =
  AuthenticatedSelfEmployedPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedInvoicesRoute =
  AuthenticatedSelfEmployedInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedIncomeRoute =
  AuthenticatedSelfEmployedIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedDocumentsRoute =
  AuthenticatedSelfEmployedDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedClientsRoute =
  AuthenticatedSelfEmployedClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedAnalyticsRoute =
  AuthenticatedSelfEmployedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedSelfEmployedAiRoute =
  AuthenticatedSelfEmployedAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedSelfEmployedRouteRoute,
  } as any)
const AuthenticatedIpWarehouseRoute =
  AuthenticatedIpWarehouseRouteImport.update({
    id: '/warehouse',
    path: '/warehouse',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpTeamRoute = AuthenticatedIpTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpTaxesRoute = AuthenticatedIpTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpSuppliersRoute =
  AuthenticatedIpSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpSettingsRoute = AuthenticatedIpSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpSbpRoute = AuthenticatedIpSbpRouteImport.update({
  id: '/sbp',
  path: '/sbp',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpSalesRoute = AuthenticatedIpSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpQrRoute = AuthenticatedIpQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpPayrollRoute = AuthenticatedIpPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpPaymentsRoute = AuthenticatedIpPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpOrdersRoute = AuthenticatedIpOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpMarketplaceRoute =
  AuthenticatedIpMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpIntegrationsRoute =
  AuthenticatedIpIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpFinanceRoute = AuthenticatedIpFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpDocumentsRoute =
  AuthenticatedIpDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpDigitalRubleRoute =
  AuthenticatedIpDigitalRubleRouteImport.update({
    id: '/digital-ruble',
    path: '/digital-ruble',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpCustomersRoute =
  AuthenticatedIpCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpCrmRoute = AuthenticatedIpCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpCatalogRoute = AuthenticatedIpCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedIpBankAccountsRoute =
  AuthenticatedIpBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpAnalyticsRoute =
  AuthenticatedIpAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedIpRouteRoute,
  } as any)
const AuthenticatedIpAiRoute = AuthenticatedIpAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedIpRouteRoute,
} as any)
const AuthenticatedCitizenWalletRoute =
  AuthenticatedCitizenWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenTransfersRoute =
  AuthenticatedCitizenTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenSupportRoute =
  AuthenticatedCitizenSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenSubscriptionsRoute =
  AuthenticatedCitizenSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenSettingsRoute =
  AuthenticatedCitizenSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenQrRoute = AuthenticatedCitizenQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedCitizenRouteRoute,
} as any)
const AuthenticatedCitizenProfileRoute =
  AuthenticatedCitizenProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenPaymentsRoute =
  AuthenticatedCitizenPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenNotificationsRoute =
  AuthenticatedCitizenNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenHistoryRoute =
  AuthenticatedCitizenHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenDocumentsRoute =
  AuthenticatedCitizenDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenAnalyticsRoute =
  AuthenticatedCitizenAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenAiRoute = AuthenticatedCitizenAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedCitizenRouteRoute,
} as any)
const AuthenticatedSelfEmployedInvoicesNewRoute =
  AuthenticatedSelfEmployedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSelfEmployedInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/business': typeof BusinessRoute
  '/citizens': typeof CitizensRoute
  '/contacts': typeof ContactsRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/citizen': typeof AuthenticatedCitizenRouteRouteWithChildren
  '/ip': typeof AuthenticatedIpRouteRouteWithChildren
  '/self-employed': typeof AuthenticatedSelfEmployedRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/citizen-ai': typeof ApiCitizenAiRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/citizen/ai': typeof AuthenticatedCitizenAiRoute
  '/citizen/analytics': typeof AuthenticatedCitizenAnalyticsRoute
  '/citizen/documents': typeof AuthenticatedCitizenDocumentsRoute
  '/citizen/history': typeof AuthenticatedCitizenHistoryRoute
  '/citizen/notifications': typeof AuthenticatedCitizenNotificationsRoute
  '/citizen/payments': typeof AuthenticatedCitizenPaymentsRoute
  '/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/citizen/qr': typeof AuthenticatedCitizenQrRoute
  '/citizen/settings': typeof AuthenticatedCitizenSettingsRoute
  '/citizen/subscriptions': typeof AuthenticatedCitizenSubscriptionsRoute
  '/citizen/support': typeof AuthenticatedCitizenSupportRoute
  '/citizen/transfers': typeof AuthenticatedCitizenTransfersRoute
  '/citizen/wallet': typeof AuthenticatedCitizenWalletRoute
  '/ip/ai': typeof AuthenticatedIpAiRoute
  '/ip/analytics': typeof AuthenticatedIpAnalyticsRoute
  '/ip/bank-accounts': typeof AuthenticatedIpBankAccountsRoute
  '/ip/catalog': typeof AuthenticatedIpCatalogRoute
  '/ip/crm': typeof AuthenticatedIpCrmRoute
  '/ip/customers': typeof AuthenticatedIpCustomersRoute
  '/ip/digital-ruble': typeof AuthenticatedIpDigitalRubleRoute
  '/ip/documents': typeof AuthenticatedIpDocumentsRoute
  '/ip/finance': typeof AuthenticatedIpFinanceRoute
  '/ip/integrations': typeof AuthenticatedIpIntegrationsRoute
  '/ip/marketplace': typeof AuthenticatedIpMarketplaceRoute
  '/ip/orders': typeof AuthenticatedIpOrdersRoute
  '/ip/payments': typeof AuthenticatedIpPaymentsRoute
  '/ip/payroll': typeof AuthenticatedIpPayrollRoute
  '/ip/qr': typeof AuthenticatedIpQrRoute
  '/ip/sales': typeof AuthenticatedIpSalesRoute
  '/ip/sbp': typeof AuthenticatedIpSbpRoute
  '/ip/settings': typeof AuthenticatedIpSettingsRoute
  '/ip/suppliers': typeof AuthenticatedIpSuppliersRoute
  '/ip/taxes': typeof AuthenticatedIpTaxesRoute
  '/ip/team': typeof AuthenticatedIpTeamRoute
  '/ip/warehouse': typeof AuthenticatedIpWarehouseRoute
  '/self-employed/ai': typeof AuthenticatedSelfEmployedAiRoute
  '/self-employed/analytics': typeof AuthenticatedSelfEmployedAnalyticsRoute
  '/self-employed/clients': typeof AuthenticatedSelfEmployedClientsRoute
  '/self-employed/documents': typeof AuthenticatedSelfEmployedDocumentsRoute
  '/self-employed/income': typeof AuthenticatedSelfEmployedIncomeRoute
  '/self-employed/invoices': typeof AuthenticatedSelfEmployedInvoicesRouteWithChildren
  '/self-employed/payments': typeof AuthenticatedSelfEmployedPaymentsRoute
  '/self-employed/qr': typeof AuthenticatedSelfEmployedQrRoute
  '/self-employed/services': typeof AuthenticatedSelfEmployedServicesRoute
  '/self-employed/settings': typeof AuthenticatedSelfEmployedSettingsRoute
  '/self-employed/support': typeof AuthenticatedSelfEmployedSupportRoute
  '/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/ip/': typeof AuthenticatedIpIndexRoute
  '/self-employed/': typeof AuthenticatedSelfEmployedIndexRoute
  '/self-employed/invoices/new': typeof AuthenticatedSelfEmployedInvoicesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/business': typeof BusinessRoute
  '/citizens': typeof CitizensRoute
  '/contacts': typeof ContactsRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/citizen-ai': typeof ApiCitizenAiRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/citizen/ai': typeof AuthenticatedCitizenAiRoute
  '/citizen/analytics': typeof AuthenticatedCitizenAnalyticsRoute
  '/citizen/documents': typeof AuthenticatedCitizenDocumentsRoute
  '/citizen/history': typeof AuthenticatedCitizenHistoryRoute
  '/citizen/notifications': typeof AuthenticatedCitizenNotificationsRoute
  '/citizen/payments': typeof AuthenticatedCitizenPaymentsRoute
  '/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/citizen/qr': typeof AuthenticatedCitizenQrRoute
  '/citizen/settings': typeof AuthenticatedCitizenSettingsRoute
  '/citizen/subscriptions': typeof AuthenticatedCitizenSubscriptionsRoute
  '/citizen/support': typeof AuthenticatedCitizenSupportRoute
  '/citizen/transfers': typeof AuthenticatedCitizenTransfersRoute
  '/citizen/wallet': typeof AuthenticatedCitizenWalletRoute
  '/ip/ai': typeof AuthenticatedIpAiRoute
  '/ip/analytics': typeof AuthenticatedIpAnalyticsRoute
  '/ip/bank-accounts': typeof AuthenticatedIpBankAccountsRoute
  '/ip/catalog': typeof AuthenticatedIpCatalogRoute
  '/ip/crm': typeof AuthenticatedIpCrmRoute
  '/ip/customers': typeof AuthenticatedIpCustomersRoute
  '/ip/digital-ruble': typeof AuthenticatedIpDigitalRubleRoute
  '/ip/documents': typeof AuthenticatedIpDocumentsRoute
  '/ip/finance': typeof AuthenticatedIpFinanceRoute
  '/ip/integrations': typeof AuthenticatedIpIntegrationsRoute
  '/ip/marketplace': typeof AuthenticatedIpMarketplaceRoute
  '/ip/orders': typeof AuthenticatedIpOrdersRoute
  '/ip/payments': typeof AuthenticatedIpPaymentsRoute
  '/ip/payroll': typeof AuthenticatedIpPayrollRoute
  '/ip/qr': typeof AuthenticatedIpQrRoute
  '/ip/sales': typeof AuthenticatedIpSalesRoute
  '/ip/sbp': typeof AuthenticatedIpSbpRoute
  '/ip/settings': typeof AuthenticatedIpSettingsRoute
  '/ip/suppliers': typeof AuthenticatedIpSuppliersRoute
  '/ip/taxes': typeof AuthenticatedIpTaxesRoute
  '/ip/team': typeof AuthenticatedIpTeamRoute
  '/ip/warehouse': typeof AuthenticatedIpWarehouseRoute
  '/self-employed/ai': typeof AuthenticatedSelfEmployedAiRoute
  '/self-employed/analytics': typeof AuthenticatedSelfEmployedAnalyticsRoute
  '/self-employed/clients': typeof AuthenticatedSelfEmployedClientsRoute
  '/self-employed/documents': typeof AuthenticatedSelfEmployedDocumentsRoute
  '/self-employed/income': typeof AuthenticatedSelfEmployedIncomeRoute
  '/self-employed/invoices': typeof AuthenticatedSelfEmployedInvoicesRouteWithChildren
  '/self-employed/payments': typeof AuthenticatedSelfEmployedPaymentsRoute
  '/self-employed/qr': typeof AuthenticatedSelfEmployedQrRoute
  '/self-employed/services': typeof AuthenticatedSelfEmployedServicesRoute
  '/self-employed/settings': typeof AuthenticatedSelfEmployedSettingsRoute
  '/self-employed/support': typeof AuthenticatedSelfEmployedSupportRoute
  '/citizen': typeof AuthenticatedCitizenIndexRoute
  '/ip': typeof AuthenticatedIpIndexRoute
  '/self-employed': typeof AuthenticatedSelfEmployedIndexRoute
  '/self-employed/invoices/new': typeof AuthenticatedSelfEmployedInvoicesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/business': typeof BusinessRoute
  '/citizens': typeof CitizensRoute
  '/contacts': typeof ContactsRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/citizen': typeof AuthenticatedCitizenRouteRouteWithChildren
  '/_authenticated/ip': typeof AuthenticatedIpRouteRouteWithChildren
  '/_authenticated/self-employed': typeof AuthenticatedSelfEmployedRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/citizen-ai': typeof ApiCitizenAiRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/citizen/ai': typeof AuthenticatedCitizenAiRoute
  '/_authenticated/citizen/analytics': typeof AuthenticatedCitizenAnalyticsRoute
  '/_authenticated/citizen/documents': typeof AuthenticatedCitizenDocumentsRoute
  '/_authenticated/citizen/history': typeof AuthenticatedCitizenHistoryRoute
  '/_authenticated/citizen/notifications': typeof AuthenticatedCitizenNotificationsRoute
  '/_authenticated/citizen/payments': typeof AuthenticatedCitizenPaymentsRoute
  '/_authenticated/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/_authenticated/citizen/qr': typeof AuthenticatedCitizenQrRoute
  '/_authenticated/citizen/settings': typeof AuthenticatedCitizenSettingsRoute
  '/_authenticated/citizen/subscriptions': typeof AuthenticatedCitizenSubscriptionsRoute
  '/_authenticated/citizen/support': typeof AuthenticatedCitizenSupportRoute
  '/_authenticated/citizen/transfers': typeof AuthenticatedCitizenTransfersRoute
  '/_authenticated/citizen/wallet': typeof AuthenticatedCitizenWalletRoute
  '/_authenticated/ip/ai': typeof AuthenticatedIpAiRoute
  '/_authenticated/ip/analytics': typeof AuthenticatedIpAnalyticsRoute
  '/_authenticated/ip/bank-accounts': typeof AuthenticatedIpBankAccountsRoute
  '/_authenticated/ip/catalog': typeof AuthenticatedIpCatalogRoute
  '/_authenticated/ip/crm': typeof AuthenticatedIpCrmRoute
  '/_authenticated/ip/customers': typeof AuthenticatedIpCustomersRoute
  '/_authenticated/ip/digital-ruble': typeof AuthenticatedIpDigitalRubleRoute
  '/_authenticated/ip/documents': typeof AuthenticatedIpDocumentsRoute
  '/_authenticated/ip/finance': typeof AuthenticatedIpFinanceRoute
  '/_authenticated/ip/integrations': typeof AuthenticatedIpIntegrationsRoute
  '/_authenticated/ip/marketplace': typeof AuthenticatedIpMarketplaceRoute
  '/_authenticated/ip/orders': typeof AuthenticatedIpOrdersRoute
  '/_authenticated/ip/payments': typeof AuthenticatedIpPaymentsRoute
  '/_authenticated/ip/payroll': typeof AuthenticatedIpPayrollRoute
  '/_authenticated/ip/qr': typeof AuthenticatedIpQrRoute
  '/_authenticated/ip/sales': typeof AuthenticatedIpSalesRoute
  '/_authenticated/ip/sbp': typeof AuthenticatedIpSbpRoute
  '/_authenticated/ip/settings': typeof AuthenticatedIpSettingsRoute
  '/_authenticated/ip/suppliers': typeof AuthenticatedIpSuppliersRoute
  '/_authenticated/ip/taxes': typeof AuthenticatedIpTaxesRoute
  '/_authenticated/ip/team': typeof AuthenticatedIpTeamRoute
  '/_authenticated/ip/warehouse': typeof AuthenticatedIpWarehouseRoute
  '/_authenticated/self-employed/ai': typeof AuthenticatedSelfEmployedAiRoute
  '/_authenticated/self-employed/analytics': typeof AuthenticatedSelfEmployedAnalyticsRoute
  '/_authenticated/self-employed/clients': typeof AuthenticatedSelfEmployedClientsRoute
  '/_authenticated/self-employed/documents': typeof AuthenticatedSelfEmployedDocumentsRoute
  '/_authenticated/self-employed/income': typeof AuthenticatedSelfEmployedIncomeRoute
  '/_authenticated/self-employed/invoices': typeof AuthenticatedSelfEmployedInvoicesRouteWithChildren
  '/_authenticated/self-employed/payments': typeof AuthenticatedSelfEmployedPaymentsRoute
  '/_authenticated/self-employed/qr': typeof AuthenticatedSelfEmployedQrRoute
  '/_authenticated/self-employed/services': typeof AuthenticatedSelfEmployedServicesRoute
  '/_authenticated/self-employed/settings': typeof AuthenticatedSelfEmployedSettingsRoute
  '/_authenticated/self-employed/support': typeof AuthenticatedSelfEmployedSupportRoute
  '/_authenticated/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/_authenticated/ip/': typeof AuthenticatedIpIndexRoute
  '/_authenticated/self-employed/': typeof AuthenticatedSelfEmployedIndexRoute
  '/_authenticated/self-employed/invoices/new': typeof AuthenticatedSelfEmployedInvoicesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/auth'
    | '/business'
    | '/citizens'
    | '/contacts'
    | '/developers'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/citizen'
    | '/ip'
    | '/self-employed'
    | '/app'
    | '/onboarding'
    | '/api/citizen-ai'
    | '/auth/register'
    | '/auth/reset-password'
    | '/citizen/ai'
    | '/citizen/analytics'
    | '/citizen/documents'
    | '/citizen/history'
    | '/citizen/notifications'
    | '/citizen/payments'
    | '/citizen/profile'
    | '/citizen/qr'
    | '/citizen/settings'
    | '/citizen/subscriptions'
    | '/citizen/support'
    | '/citizen/transfers'
    | '/citizen/wallet'
    | '/ip/ai'
    | '/ip/analytics'
    | '/ip/bank-accounts'
    | '/ip/catalog'
    | '/ip/crm'
    | '/ip/customers'
    | '/ip/digital-ruble'
    | '/ip/documents'
    | '/ip/finance'
    | '/ip/integrations'
    | '/ip/marketplace'
    | '/ip/orders'
    | '/ip/payments'
    | '/ip/payroll'
    | '/ip/qr'
    | '/ip/sales'
    | '/ip/sbp'
    | '/ip/settings'
    | '/ip/suppliers'
    | '/ip/taxes'
    | '/ip/team'
    | '/ip/warehouse'
    | '/self-employed/ai'
    | '/self-employed/analytics'
    | '/self-employed/clients'
    | '/self-employed/documents'
    | '/self-employed/income'
    | '/self-employed/invoices'
    | '/self-employed/payments'
    | '/self-employed/qr'
    | '/self-employed/services'
    | '/self-employed/settings'
    | '/self-employed/support'
    | '/citizen/'
    | '/ip/'
    | '/self-employed/'
    | '/self-employed/invoices/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/auth'
    | '/business'
    | '/citizens'
    | '/contacts'
    | '/developers'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/app'
    | '/onboarding'
    | '/api/citizen-ai'
    | '/auth/register'
    | '/auth/reset-password'
    | '/citizen/ai'
    | '/citizen/analytics'
    | '/citizen/documents'
    | '/citizen/history'
    | '/citizen/notifications'
    | '/citizen/payments'
    | '/citizen/profile'
    | '/citizen/qr'
    | '/citizen/settings'
    | '/citizen/subscriptions'
    | '/citizen/support'
    | '/citizen/transfers'
    | '/citizen/wallet'
    | '/ip/ai'
    | '/ip/analytics'
    | '/ip/bank-accounts'
    | '/ip/catalog'
    | '/ip/crm'
    | '/ip/customers'
    | '/ip/digital-ruble'
    | '/ip/documents'
    | '/ip/finance'
    | '/ip/integrations'
    | '/ip/marketplace'
    | '/ip/orders'
    | '/ip/payments'
    | '/ip/payroll'
    | '/ip/qr'
    | '/ip/sales'
    | '/ip/sbp'
    | '/ip/settings'
    | '/ip/suppliers'
    | '/ip/taxes'
    | '/ip/team'
    | '/ip/warehouse'
    | '/self-employed/ai'
    | '/self-employed/analytics'
    | '/self-employed/clients'
    | '/self-employed/documents'
    | '/self-employed/income'
    | '/self-employed/invoices'
    | '/self-employed/payments'
    | '/self-employed/qr'
    | '/self-employed/services'
    | '/self-employed/settings'
    | '/self-employed/support'
    | '/citizen'
    | '/ip'
    | '/self-employed'
    | '/self-employed/invoices/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api'
    | '/auth'
    | '/business'
    | '/citizens'
    | '/contacts'
    | '/developers'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/support'
    | '/terms'
    | '/_authenticated/citizen'
    | '/_authenticated/ip'
    | '/_authenticated/self-employed'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/api/citizen-ai'
    | '/auth/register'
    | '/auth/reset-password'
    | '/_authenticated/citizen/ai'
    | '/_authenticated/citizen/analytics'
    | '/_authenticated/citizen/documents'
    | '/_authenticated/citizen/history'
    | '/_authenticated/citizen/notifications'
    | '/_authenticated/citizen/payments'
    | '/_authenticated/citizen/profile'
    | '/_authenticated/citizen/qr'
    | '/_authenticated/citizen/settings'
    | '/_authenticated/citizen/subscriptions'
    | '/_authenticated/citizen/support'
    | '/_authenticated/citizen/transfers'
    | '/_authenticated/citizen/wallet'
    | '/_authenticated/ip/ai'
    | '/_authenticated/ip/analytics'
    | '/_authenticated/ip/bank-accounts'
    | '/_authenticated/ip/catalog'
    | '/_authenticated/ip/crm'
    | '/_authenticated/ip/customers'
    | '/_authenticated/ip/digital-ruble'
    | '/_authenticated/ip/documents'
    | '/_authenticated/ip/finance'
    | '/_authenticated/ip/integrations'
    | '/_authenticated/ip/marketplace'
    | '/_authenticated/ip/orders'
    | '/_authenticated/ip/payments'
    | '/_authenticated/ip/payroll'
    | '/_authenticated/ip/qr'
    | '/_authenticated/ip/sales'
    | '/_authenticated/ip/sbp'
    | '/_authenticated/ip/settings'
    | '/_authenticated/ip/suppliers'
    | '/_authenticated/ip/taxes'
    | '/_authenticated/ip/team'
    | '/_authenticated/ip/warehouse'
    | '/_authenticated/self-employed/ai'
    | '/_authenticated/self-employed/analytics'
    | '/_authenticated/self-employed/clients'
    | '/_authenticated/self-employed/documents'
    | '/_authenticated/self-employed/income'
    | '/_authenticated/self-employed/invoices'
    | '/_authenticated/self-employed/payments'
    | '/_authenticated/self-employed/qr'
    | '/_authenticated/self-employed/services'
    | '/_authenticated/self-employed/settings'
    | '/_authenticated/self-employed/support'
    | '/_authenticated/citizen/'
    | '/_authenticated/ip/'
    | '/_authenticated/self-employed/'
    | '/_authenticated/self-employed/invoices/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiRoute: typeof ApiRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  CitizensRoute: typeof CitizensRoute
  ContactsRoute: typeof ContactsRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizens': {
      id: '/citizens'
      path: '/citizens'
      fullPath: '/citizens'
      preLoaderRoute: typeof CitizensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/citizen-ai': {
      id: '/api/citizen-ai'
      path: '/citizen-ai'
      fullPath: '/api/citizen-ai'
      preLoaderRoute: typeof ApiCitizenAiRouteImport
      parentRoute: typeof ApiRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/self-employed': {
      id: '/_authenticated/self-employed'
      path: '/self-employed'
      fullPath: '/self-employed'
      preLoaderRoute: typeof AuthenticatedSelfEmployedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ip': {
      id: '/_authenticated/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof AuthenticatedIpRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen': {
      id: '/_authenticated/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof AuthenticatedCitizenRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/self-employed/': {
      id: '/_authenticated/self-employed/'
      path: '/'
      fullPath: '/self-employed/'
      preLoaderRoute: typeof AuthenticatedSelfEmployedIndexRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/ip/': {
      id: '/_authenticated/ip/'
      path: '/'
      fullPath: '/ip/'
      preLoaderRoute: typeof AuthenticatedIpIndexRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/citizen/': {
      id: '/_authenticated/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof AuthenticatedCitizenIndexRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/self-employed/support': {
      id: '/_authenticated/self-employed/support'
      path: '/support'
      fullPath: '/self-employed/support'
      preLoaderRoute: typeof AuthenticatedSelfEmployedSupportRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/settings': {
      id: '/_authenticated/self-employed/settings'
      path: '/settings'
      fullPath: '/self-employed/settings'
      preLoaderRoute: typeof AuthenticatedSelfEmployedSettingsRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/services': {
      id: '/_authenticated/self-employed/services'
      path: '/services'
      fullPath: '/self-employed/services'
      preLoaderRoute: typeof AuthenticatedSelfEmployedServicesRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/qr': {
      id: '/_authenticated/self-employed/qr'
      path: '/qr'
      fullPath: '/self-employed/qr'
      preLoaderRoute: typeof AuthenticatedSelfEmployedQrRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/payments': {
      id: '/_authenticated/self-employed/payments'
      path: '/payments'
      fullPath: '/self-employed/payments'
      preLoaderRoute: typeof AuthenticatedSelfEmployedPaymentsRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/invoices': {
      id: '/_authenticated/self-employed/invoices'
      path: '/invoices'
      fullPath: '/self-employed/invoices'
      preLoaderRoute: typeof AuthenticatedSelfEmployedInvoicesRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/income': {
      id: '/_authenticated/self-employed/income'
      path: '/income'
      fullPath: '/self-employed/income'
      preLoaderRoute: typeof AuthenticatedSelfEmployedIncomeRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/documents': {
      id: '/_authenticated/self-employed/documents'
      path: '/documents'
      fullPath: '/self-employed/documents'
      preLoaderRoute: typeof AuthenticatedSelfEmployedDocumentsRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/clients': {
      id: '/_authenticated/self-employed/clients'
      path: '/clients'
      fullPath: '/self-employed/clients'
      preLoaderRoute: typeof AuthenticatedSelfEmployedClientsRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/analytics': {
      id: '/_authenticated/self-employed/analytics'
      path: '/analytics'
      fullPath: '/self-employed/analytics'
      preLoaderRoute: typeof AuthenticatedSelfEmployedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/self-employed/ai': {
      id: '/_authenticated/self-employed/ai'
      path: '/ai'
      fullPath: '/self-employed/ai'
      preLoaderRoute: typeof AuthenticatedSelfEmployedAiRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedRouteRoute
    }
    '/_authenticated/ip/warehouse': {
      id: '/_authenticated/ip/warehouse'
      path: '/warehouse'
      fullPath: '/ip/warehouse'
      preLoaderRoute: typeof AuthenticatedIpWarehouseRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/team': {
      id: '/_authenticated/ip/team'
      path: '/team'
      fullPath: '/ip/team'
      preLoaderRoute: typeof AuthenticatedIpTeamRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/taxes': {
      id: '/_authenticated/ip/taxes'
      path: '/taxes'
      fullPath: '/ip/taxes'
      preLoaderRoute: typeof AuthenticatedIpTaxesRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/suppliers': {
      id: '/_authenticated/ip/suppliers'
      path: '/suppliers'
      fullPath: '/ip/suppliers'
      preLoaderRoute: typeof AuthenticatedIpSuppliersRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/settings': {
      id: '/_authenticated/ip/settings'
      path: '/settings'
      fullPath: '/ip/settings'
      preLoaderRoute: typeof AuthenticatedIpSettingsRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/sbp': {
      id: '/_authenticated/ip/sbp'
      path: '/sbp'
      fullPath: '/ip/sbp'
      preLoaderRoute: typeof AuthenticatedIpSbpRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/sales': {
      id: '/_authenticated/ip/sales'
      path: '/sales'
      fullPath: '/ip/sales'
      preLoaderRoute: typeof AuthenticatedIpSalesRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/qr': {
      id: '/_authenticated/ip/qr'
      path: '/qr'
      fullPath: '/ip/qr'
      preLoaderRoute: typeof AuthenticatedIpQrRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/payroll': {
      id: '/_authenticated/ip/payroll'
      path: '/payroll'
      fullPath: '/ip/payroll'
      preLoaderRoute: typeof AuthenticatedIpPayrollRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/payments': {
      id: '/_authenticated/ip/payments'
      path: '/payments'
      fullPath: '/ip/payments'
      preLoaderRoute: typeof AuthenticatedIpPaymentsRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/orders': {
      id: '/_authenticated/ip/orders'
      path: '/orders'
      fullPath: '/ip/orders'
      preLoaderRoute: typeof AuthenticatedIpOrdersRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/marketplace': {
      id: '/_authenticated/ip/marketplace'
      path: '/marketplace'
      fullPath: '/ip/marketplace'
      preLoaderRoute: typeof AuthenticatedIpMarketplaceRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/integrations': {
      id: '/_authenticated/ip/integrations'
      path: '/integrations'
      fullPath: '/ip/integrations'
      preLoaderRoute: typeof AuthenticatedIpIntegrationsRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/finance': {
      id: '/_authenticated/ip/finance'
      path: '/finance'
      fullPath: '/ip/finance'
      preLoaderRoute: typeof AuthenticatedIpFinanceRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/documents': {
      id: '/_authenticated/ip/documents'
      path: '/documents'
      fullPath: '/ip/documents'
      preLoaderRoute: typeof AuthenticatedIpDocumentsRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/digital-ruble': {
      id: '/_authenticated/ip/digital-ruble'
      path: '/digital-ruble'
      fullPath: '/ip/digital-ruble'
      preLoaderRoute: typeof AuthenticatedIpDigitalRubleRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/customers': {
      id: '/_authenticated/ip/customers'
      path: '/customers'
      fullPath: '/ip/customers'
      preLoaderRoute: typeof AuthenticatedIpCustomersRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/crm': {
      id: '/_authenticated/ip/crm'
      path: '/crm'
      fullPath: '/ip/crm'
      preLoaderRoute: typeof AuthenticatedIpCrmRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/catalog': {
      id: '/_authenticated/ip/catalog'
      path: '/catalog'
      fullPath: '/ip/catalog'
      preLoaderRoute: typeof AuthenticatedIpCatalogRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/bank-accounts': {
      id: '/_authenticated/ip/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/ip/bank-accounts'
      preLoaderRoute: typeof AuthenticatedIpBankAccountsRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/analytics': {
      id: '/_authenticated/ip/analytics'
      path: '/analytics'
      fullPath: '/ip/analytics'
      preLoaderRoute: typeof AuthenticatedIpAnalyticsRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/ip/ai': {
      id: '/_authenticated/ip/ai'
      path: '/ai'
      fullPath: '/ip/ai'
      preLoaderRoute: typeof AuthenticatedIpAiRouteImport
      parentRoute: typeof AuthenticatedIpRouteRoute
    }
    '/_authenticated/citizen/wallet': {
      id: '/_authenticated/citizen/wallet'
      path: '/wallet'
      fullPath: '/citizen/wallet'
      preLoaderRoute: typeof AuthenticatedCitizenWalletRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/transfers': {
      id: '/_authenticated/citizen/transfers'
      path: '/transfers'
      fullPath: '/citizen/transfers'
      preLoaderRoute: typeof AuthenticatedCitizenTransfersRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/support': {
      id: '/_authenticated/citizen/support'
      path: '/support'
      fullPath: '/citizen/support'
      preLoaderRoute: typeof AuthenticatedCitizenSupportRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/subscriptions': {
      id: '/_authenticated/citizen/subscriptions'
      path: '/subscriptions'
      fullPath: '/citizen/subscriptions'
      preLoaderRoute: typeof AuthenticatedCitizenSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/settings': {
      id: '/_authenticated/citizen/settings'
      path: '/settings'
      fullPath: '/citizen/settings'
      preLoaderRoute: typeof AuthenticatedCitizenSettingsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/qr': {
      id: '/_authenticated/citizen/qr'
      path: '/qr'
      fullPath: '/citizen/qr'
      preLoaderRoute: typeof AuthenticatedCitizenQrRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/profile': {
      id: '/_authenticated/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof AuthenticatedCitizenProfileRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/payments': {
      id: '/_authenticated/citizen/payments'
      path: '/payments'
      fullPath: '/citizen/payments'
      preLoaderRoute: typeof AuthenticatedCitizenPaymentsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/notifications': {
      id: '/_authenticated/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof AuthenticatedCitizenNotificationsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/history': {
      id: '/_authenticated/citizen/history'
      path: '/history'
      fullPath: '/citizen/history'
      preLoaderRoute: typeof AuthenticatedCitizenHistoryRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/documents': {
      id: '/_authenticated/citizen/documents'
      path: '/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof AuthenticatedCitizenDocumentsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/analytics': {
      id: '/_authenticated/citizen/analytics'
      path: '/analytics'
      fullPath: '/citizen/analytics'
      preLoaderRoute: typeof AuthenticatedCitizenAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/ai': {
      id: '/_authenticated/citizen/ai'
      path: '/ai'
      fullPath: '/citizen/ai'
      preLoaderRoute: typeof AuthenticatedCitizenAiRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/self-employed/invoices/new': {
      id: '/_authenticated/self-employed/invoices/new'
      path: '/new'
      fullPath: '/self-employed/invoices/new'
      preLoaderRoute: typeof AuthenticatedSelfEmployedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedSelfEmployedInvoicesRoute
    }
  }
}

interface AuthenticatedCitizenRouteRouteChildren {
  AuthenticatedCitizenAiRoute: typeof AuthenticatedCitizenAiRoute
  AuthenticatedCitizenAnalyticsRoute: typeof AuthenticatedCitizenAnalyticsRoute
  AuthenticatedCitizenDocumentsRoute: typeof AuthenticatedCitizenDocumentsRoute
  AuthenticatedCitizenHistoryRoute: typeof AuthenticatedCitizenHistoryRoute
  AuthenticatedCitizenNotificationsRoute: typeof AuthenticatedCitizenNotificationsRoute
  AuthenticatedCitizenPaymentsRoute: typeof AuthenticatedCitizenPaymentsRoute
  AuthenticatedCitizenProfileRoute: typeof AuthenticatedCitizenProfileRoute
  AuthenticatedCitizenQrRoute: typeof AuthenticatedCitizenQrRoute
  AuthenticatedCitizenSettingsRoute: typeof AuthenticatedCitizenSettingsRoute
  AuthenticatedCitizenSubscriptionsRoute: typeof AuthenticatedCitizenSubscriptionsRoute
  AuthenticatedCitizenSupportRoute: typeof AuthenticatedCitizenSupportRoute
  AuthenticatedCitizenTransfersRoute: typeof AuthenticatedCitizenTransfersRoute
  AuthenticatedCitizenWalletRoute: typeof AuthenticatedCitizenWalletRoute
  AuthenticatedCitizenIndexRoute: typeof AuthenticatedCitizenIndexRoute
}

const AuthenticatedCitizenRouteRouteChildren: AuthenticatedCitizenRouteRouteChildren =
  {
    AuthenticatedCitizenAiRoute: AuthenticatedCitizenAiRoute,
    AuthenticatedCitizenAnalyticsRoute: AuthenticatedCitizenAnalyticsRoute,
    AuthenticatedCitizenDocumentsRoute: AuthenticatedCitizenDocumentsRoute,
    AuthenticatedCitizenHistoryRoute: AuthenticatedCitizenHistoryRoute,
    AuthenticatedCitizenNotificationsRoute:
      AuthenticatedCitizenNotificationsRoute,
    AuthenticatedCitizenPaymentsRoute: AuthenticatedCitizenPaymentsRoute,
    AuthenticatedCitizenProfileRoute: AuthenticatedCitizenProfileRoute,
    AuthenticatedCitizenQrRoute: AuthenticatedCitizenQrRoute,
    AuthenticatedCitizenSettingsRoute: AuthenticatedCitizenSettingsRoute,
    AuthenticatedCitizenSubscriptionsRoute:
      AuthenticatedCitizenSubscriptionsRoute,
    AuthenticatedCitizenSupportRoute: AuthenticatedCitizenSupportRoute,
    AuthenticatedCitizenTransfersRoute: AuthenticatedCitizenTransfersRoute,
    AuthenticatedCitizenWalletRoute: AuthenticatedCitizenWalletRoute,
    AuthenticatedCitizenIndexRoute: AuthenticatedCitizenIndexRoute,
  }

const AuthenticatedCitizenRouteRouteWithChildren =
  AuthenticatedCitizenRouteRoute._addFileChildren(
    AuthenticatedCitizenRouteRouteChildren,
  )

interface AuthenticatedIpRouteRouteChildren {
  AuthenticatedIpAiRoute: typeof AuthenticatedIpAiRoute
  AuthenticatedIpAnalyticsRoute: typeof AuthenticatedIpAnalyticsRoute
  AuthenticatedIpBankAccountsRoute: typeof AuthenticatedIpBankAccountsRoute
  AuthenticatedIpCatalogRoute: typeof AuthenticatedIpCatalogRoute
  AuthenticatedIpCrmRoute: typeof AuthenticatedIpCrmRoute
  AuthenticatedIpCustomersRoute: typeof AuthenticatedIpCustomersRoute
  AuthenticatedIpDigitalRubleRoute: typeof AuthenticatedIpDigitalRubleRoute
  AuthenticatedIpDocumentsRoute: typeof AuthenticatedIpDocumentsRoute
  AuthenticatedIpFinanceRoute: typeof AuthenticatedIpFinanceRoute
  AuthenticatedIpIntegrationsRoute: typeof AuthenticatedIpIntegrationsRoute
  AuthenticatedIpMarketplaceRoute: typeof AuthenticatedIpMarketplaceRoute
  AuthenticatedIpOrdersRoute: typeof AuthenticatedIpOrdersRoute
  AuthenticatedIpPaymentsRoute: typeof AuthenticatedIpPaymentsRoute
  AuthenticatedIpPayrollRoute: typeof AuthenticatedIpPayrollRoute
  AuthenticatedIpQrRoute: typeof AuthenticatedIpQrRoute
  AuthenticatedIpSalesRoute: typeof AuthenticatedIpSalesRoute
  AuthenticatedIpSbpRoute: typeof AuthenticatedIpSbpRoute
  AuthenticatedIpSettingsRoute: typeof AuthenticatedIpSettingsRoute
  AuthenticatedIpSuppliersRoute: typeof AuthenticatedIpSuppliersRoute
  AuthenticatedIpTaxesRoute: typeof AuthenticatedIpTaxesRoute
  AuthenticatedIpTeamRoute: typeof AuthenticatedIpTeamRoute
  AuthenticatedIpWarehouseRoute: typeof AuthenticatedIpWarehouseRoute
  AuthenticatedIpIndexRoute: typeof AuthenticatedIpIndexRoute
}

const AuthenticatedIpRouteRouteChildren: AuthenticatedIpRouteRouteChildren = {
  AuthenticatedIpAiRoute: AuthenticatedIpAiRoute,
  AuthenticatedIpAnalyticsRoute: AuthenticatedIpAnalyticsRoute,
  AuthenticatedIpBankAccountsRoute: AuthenticatedIpBankAccountsRoute,
  AuthenticatedIpCatalogRoute: AuthenticatedIpCatalogRoute,
  AuthenticatedIpCrmRoute: AuthenticatedIpCrmRoute,
  AuthenticatedIpCustomersRoute: AuthenticatedIpCustomersRoute,
  AuthenticatedIpDigitalRubleRoute: AuthenticatedIpDigitalRubleRoute,
  AuthenticatedIpDocumentsRoute: AuthenticatedIpDocumentsRoute,
  AuthenticatedIpFinanceRoute: AuthenticatedIpFinanceRoute,
  AuthenticatedIpIntegrationsRoute: AuthenticatedIpIntegrationsRoute,
  AuthenticatedIpMarketplaceRoute: AuthenticatedIpMarketplaceRoute,
  AuthenticatedIpOrdersRoute: AuthenticatedIpOrdersRoute,
  AuthenticatedIpPaymentsRoute: AuthenticatedIpPaymentsRoute,
  AuthenticatedIpPayrollRoute: AuthenticatedIpPayrollRoute,
  AuthenticatedIpQrRoute: AuthenticatedIpQrRoute,
  AuthenticatedIpSalesRoute: AuthenticatedIpSalesRoute,
  AuthenticatedIpSbpRoute: AuthenticatedIpSbpRoute,
  AuthenticatedIpSettingsRoute: AuthenticatedIpSettingsRoute,
  AuthenticatedIpSuppliersRoute: AuthenticatedIpSuppliersRoute,
  AuthenticatedIpTaxesRoute: AuthenticatedIpTaxesRoute,
  AuthenticatedIpTeamRoute: AuthenticatedIpTeamRoute,
  AuthenticatedIpWarehouseRoute: AuthenticatedIpWarehouseRoute,
  AuthenticatedIpIndexRoute: AuthenticatedIpIndexRoute,
}

const AuthenticatedIpRouteRouteWithChildren =
  AuthenticatedIpRouteRoute._addFileChildren(AuthenticatedIpRouteRouteChildren)

interface AuthenticatedSelfEmployedInvoicesRouteChildren {
  AuthenticatedSelfEmployedInvoicesNewRoute: typeof AuthenticatedSelfEmployedInvoicesNewRoute
}

const AuthenticatedSelfEmployedInvoicesRouteChildren: AuthenticatedSelfEmployedInvoicesRouteChildren =
  {
    AuthenticatedSelfEmployedInvoicesNewRoute:
      AuthenticatedSelfEmployedInvoicesNewRoute,
  }

const AuthenticatedSelfEmployedInvoicesRouteWithChildren =
  AuthenticatedSelfEmployedInvoicesRoute._addFileChildren(
    AuthenticatedSelfEmployedInvoicesRouteChildren,
  )

interface AuthenticatedSelfEmployedRouteRouteChildren {
  AuthenticatedSelfEmployedAiRoute: typeof AuthenticatedSelfEmployedAiRoute
  AuthenticatedSelfEmployedAnalyticsRoute: typeof AuthenticatedSelfEmployedAnalyticsRoute
  AuthenticatedSelfEmployedClientsRoute: typeof AuthenticatedSelfEmployedClientsRoute
  AuthenticatedSelfEmployedDocumentsRoute: typeof AuthenticatedSelfEmployedDocumentsRoute
  AuthenticatedSelfEmployedIncomeRoute: typeof AuthenticatedSelfEmployedIncomeRoute
  AuthenticatedSelfEmployedInvoicesRoute: typeof AuthenticatedSelfEmployedInvoicesRouteWithChildren
  AuthenticatedSelfEmployedPaymentsRoute: typeof AuthenticatedSelfEmployedPaymentsRoute
  AuthenticatedSelfEmployedQrRoute: typeof AuthenticatedSelfEmployedQrRoute
  AuthenticatedSelfEmployedServicesRoute: typeof AuthenticatedSelfEmployedServicesRoute
  AuthenticatedSelfEmployedSettingsRoute: typeof AuthenticatedSelfEmployedSettingsRoute
  AuthenticatedSelfEmployedSupportRoute: typeof AuthenticatedSelfEmployedSupportRoute
  AuthenticatedSelfEmployedIndexRoute: typeof AuthenticatedSelfEmployedIndexRoute
}

const AuthenticatedSelfEmployedRouteRouteChildren: AuthenticatedSelfEmployedRouteRouteChildren =
  {
    AuthenticatedSelfEmployedAiRoute: AuthenticatedSelfEmployedAiRoute,
    AuthenticatedSelfEmployedAnalyticsRoute:
      AuthenticatedSelfEmployedAnalyticsRoute,
    AuthenticatedSelfEmployedClientsRoute:
      AuthenticatedSelfEmployedClientsRoute,
    AuthenticatedSelfEmployedDocumentsRoute:
      AuthenticatedSelfEmployedDocumentsRoute,
    AuthenticatedSelfEmployedIncomeRoute: AuthenticatedSelfEmployedIncomeRoute,
    AuthenticatedSelfEmployedInvoicesRoute:
      AuthenticatedSelfEmployedInvoicesRouteWithChildren,
    AuthenticatedSelfEmployedPaymentsRoute:
      AuthenticatedSelfEmployedPaymentsRoute,
    AuthenticatedSelfEmployedQrRoute: AuthenticatedSelfEmployedQrRoute,
    AuthenticatedSelfEmployedServicesRoute:
      AuthenticatedSelfEmployedServicesRoute,
    AuthenticatedSelfEmployedSettingsRoute:
      AuthenticatedSelfEmployedSettingsRoute,
    AuthenticatedSelfEmployedSupportRoute:
      AuthenticatedSelfEmployedSupportRoute,
    AuthenticatedSelfEmployedIndexRoute: AuthenticatedSelfEmployedIndexRoute,
  }

const AuthenticatedSelfEmployedRouteRouteWithChildren =
  AuthenticatedSelfEmployedRouteRoute._addFileChildren(
    AuthenticatedSelfEmployedRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCitizenRouteRoute: typeof AuthenticatedCitizenRouteRouteWithChildren
  AuthenticatedIpRouteRoute: typeof AuthenticatedIpRouteRouteWithChildren
  AuthenticatedSelfEmployedRouteRoute: typeof AuthenticatedSelfEmployedRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCitizenRouteRoute: AuthenticatedCitizenRouteRouteWithChildren,
  AuthenticatedIpRouteRoute: AuthenticatedIpRouteRouteWithChildren,
  AuthenticatedSelfEmployedRouteRoute:
    AuthenticatedSelfEmployedRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiRouteChildren {
  ApiCitizenAiRoute: typeof ApiCitizenAiRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiCitizenAiRoute: ApiCitizenAiRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface AuthRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiRoute: ApiRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BusinessRoute: BusinessRoute,
  CitizensRoute: CitizensRoute,
  ContactsRoute: ContactsRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
